#pragma once

/// 00 Series
#define FILEMENU_NEW 0
#define FILEMENU_OPEN 1
#define FILEMENU_SAVE 2
#define FILEMENU_SAVEAS 3
#define FILEMENU_EXIT 4


/// 100 Series
#define EDITMENU_CREATENEW 100
#define EDITMENU_UNDO 101
#define EDITMENU_REDO 102
#define EDITMENU_CUT 103
#define EDITMENU_COPY 104
#define EDITMENU_PASTE 105
#define EDITMENU_DELETE 106
/// 110 Series
#define EDITMENU_CREATENEW_PLANE 110
#define EDITMENU_CREATENEW_CUBE 111
#define EDITMENU_CREATENEW_PYRAMID 112
#define EDITMENU_CREATENEW_SPHERE 113
#define EDITMENU_CREATENEW_HEXAGON 114
#define EDITMENU_CREATENEW_CYLINDER 115


/// 200 Series
#define HELPMENU_ABOUT 200